### PR TITLE
Migrate to docrine/dbal 3

### PR DESCRIPTION
**Pull request by drewblin**
Получается мажорный релиз. Но непонятно куда сделать ПР

### CODE REVIEW

**Comment by andrew-demb** [comment]
You can check Sentry's way to implement tracing for `doctrine/dbal` to make it more clear (using new provided extension points from `doctrine/dbal`, like middlewares - https://www.doctrine-project.org/projects/doctrine-dbal/en/3.2/reference/architecture.html#middlewares).

I think we should not preserve compatibility for `doctrine/dbal` v2 since it is not maintained anymore (let's don't try to do it, as the Sentry team did).
And we can drop two different ways for injection tracing in favor of only one (middleware one) - so it will allow dropping Symfony bundle configuration too.

@allflame  @drewblin what do you think?

**Comment by drewblin** [comment]
I think doctrine middlewares is the best way to implement decorators. I will make changes to PR and leave only one way to decorate doctrine.

As for me, we can drop support for dbal v2. There is no frequently changes to this project. So even if we need to make some changes for dbal v2, it will not take too many time to support two versions for some criticals

**Comment by allflame** [comment]
Added 2.0.x so you can change base branch

**Comment by drewblin** [comment]
Done
Checked without bundle - it works

**Review by andrew-demb — APPROVED** [review]

**Pull request merged**
